### ISSUE TITLE
[feature-request] preview panel on the right side

### ISSUE THREAD

**Issue by hiepxanh** [dynamic-forms/dynamic-forms#267]
I think preview panel on the right is such amazing feature. What do you think about it?
![image](https://user-images.githubusercontent.com/16970990/174519578-af40b45b-fc03-4dd3-b71d-2a84ba1687a1.png)

BTW, in my life, the first time I can see the most complex structure of form you can built like this. Thank for your effort @AlexanderGebuhr

**Comment by AlexanderGebuhr** [comment]
That's a good idea for an UX improvement. Will check how to achieve your request.

**Comment by AlexanderGebuhr** [comment]
The feature is implemented by introducing preferences that are persisted to the local storage by using the storage plugin of [NGXS](https://github.com/ngxs/store): 
![dynamic-forms - split view](https://user-images.githubusercontent.com/65446776/174723506-79b1329c-3021-4890-afc6-2a763ca9d138.gif)
Thanks to @hiepxanh for that idea.

**Comment by hiepxanh** [comment]
Wow, that so fast, you code like flash running, thank you <3
